version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: topic3Database
    restart: always
    environment:
      POSTGRES_USER: user4topic3
      POSTGRES_PASSWORD: passtop3
      POSTGRES_DB: topic3db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: